name: Retrain StudentsPerformance Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"

      # Check Environment
      - name: Check Env
        run: |
          python --version
          pip --version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r Workflow-CI/MLProject/requirements.txt
          pip install mlflow

      # Ensure dataset exists
      - name: Check dataset
        run: |
          echo "Checking dataset..."
          if [ ! -f "namadataset_raw/StudentsPerformance.csv" ]; then
            echo "Dataset StudentsPerformance.csv NOT FOUND!"
            exit 1
          fi
          echo "Dataset found"

      # Run preprocessing script
      - name: Run preprocessing
        run: |
          echo "Running preprocessing..."
          python preprocessing/automate_rahmi.py \
            --input namadataset_raw/StudentsPerformance.csv \
            --output preprocessing/StudentsPerformance_preprocessing/dataset_preprocessed.csv
          echo "Preprocessing completed."

      # Run MLflow training project
      - name: Run mlflow project
        run: |
          cd Workflow-CI/MLProject
          echo "Starting MLflow training..."
          mlflow run . \
            -P input="../preprocessing/StudentsPerformance_preprocessing/dataset_preprocessed.csv" \
            -P target="math score"
          echo "Training completed."

      # Get latest MLflow run ID
      - name: Get latest MLflow run_id
        run: |
          echo "Retrieving latest MLflow run ID..."
          ls -R Workflow-CI/MLProject/mlruns || echo "No mlruns directory found!"
